mtk_devices:
  patterns:
    - '- hotspot'
    - '- monitoring'
    - '+ error'
    - '+ logged'
    - '+ warning'
    - '+ down'
    - '+ rebooted'
    - '+ critical'
    - '+ failure'


  vars:
    telegram_token: 795xxxx:AAExxxxxxxxxxxxxxxxx
    telegran_chatid: '-10xxxxxxxxx'


  hosts:
    host_1:
      mtk_host: 10.0.0.1
      mtk_port: 1707
      mtk_username: monitor
      mtk_password: 123123

    host_2:
      mtk_host: 172.16.177.74
      mtk_port: 22
      mtk_username: monitor
      mtk_password: 123123

  